-- Alumni Demo Data
-- Password for all accounts is 'password123' (BCrypt hashed)

INSERT INTO alumni (enrollment_number, name, email, password, passing_year, department, employment_status, bio) VALUES
('AL-2019-001', 'Rohit Mehta', 'rohit.mehta@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2019', 'Computer Science', 'EMPLOYED', 'Passionate software engineer specializing in machine learning and artificial intelligence. Experienced in Python, TensorFlow, and deep learning frameworks. Love building scalable AI solutions.'),
('AL-2020-002', 'Neha Gupta', 'neha.gupta@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2020', 'Information Technology', 'EMPLOYED', 'Full-stack developer with expertise in React, Node.js, and cloud technologies. Currently working on microservices architecture and DevOps automation. Always eager to mentor juniors.'),
('AL-2020-003', 'Amit Patel', 'amit.patel@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2020', 'Electrical Engineering', 'EMPLOYED', 'Power systems engineer working on renewable energy projects. Specialized in solar panel design and smart grid technologies. Interested in sustainable energy solutions.'),
('AL-2021-004', 'Sneha Joshi', 'sneha.joshi@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2021', 'Civil Engineering', 'SEEKING_OPPORTUNITIES', 'Recently graduated civil engineer seeking opportunities in structural design and construction management. Strong foundation in AutoCAD and structural analysis software.'),
('AL-2021-005', 'Rahul Khanna', 'rahul.khanna@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2021', 'Mechanical Engineering', 'EMPLOYED', 'Automotive engineer focused on vehicle dynamics and engine optimization. Working with CAD/CAM tools and thermal analysis. Passionate about electric vehicle technology.'),
('AL-2022-006', 'Pooja Malhotra', 'pooja.malhotra@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2022', 'Computer Science', 'SELF_EMPLOYED', 'Freelance mobile app developer specializing in Flutter and React Native. Built over 15 successful apps for startups. Available for consulting and project collaborations.'),
('AL-2018-007', 'Kunal Singh', 'kunal.singh@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2018', 'Electronics Engineering', 'EMPLOYED', 'Embedded systems engineer with expertise in IoT devices and firmware development. Proficient in C/C++, Arduino, and Raspberry Pi. Working on smart home automation systems.'),
('AL-2019-008', 'Anjali Rao', 'anjali.rao@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2019', 'Information Technology', 'EMPLOYED', 'Data analyst turned data scientist. Skilled in SQL, Python, R, and data visualization tools like Tableau and Power BI. Love uncovering insights from complex datasets.'),
('AL-2020-009', 'Vikas Yadav', 'vikas.yadav@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2020', 'Mechanical Engineering', 'SEEKING_OPPORTUNITIES', 'Mechanical design engineer with CAD expertise. Looking for opportunities in product design and manufacturing. Interested in additive manufacturing and 3D printing.'),
('AL-2022-010', 'Isha Kapoor', 'isha.kapoor@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2022', 'Computer Science', 'EMPLOYED', 'Cybersecurity specialist focusing on ethical hacking and penetration testing. Certified in CEH and OSCP. Passionate about securing web applications and networks.'),
('AL-2018-011', 'Siddharth Jain', 'siddharth.jain@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2018', 'Civil Engineering', 'EMPLOYED', 'Project manager in infrastructure development with 5+ years experience. Skilled in project planning, cost estimation, and construction supervision. PMP certified.'),
('AL-2019-012', 'Riya Bansal', 'riya.bansal@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2019', 'Electronics Engineering', 'SELF_EMPLOYED', 'Hardware entrepreneur building custom PCB designs for robotics applications. Running my own electronics consulting firm. Expert in circuit design and prototyping.'),
('AL-2021-013', 'Manish Verma', 'manish.verma@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2021', 'Electrical Engineering', 'EMPLOYED', 'Control systems engineer working on industrial automation. Experience with PLCs, SCADA systems, and process control. Interested in robotics and automation.'),
('AL-2022-014', 'Kriti Agarwal', 'kriti.agarwal@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2022', 'Information Technology', 'EMPLOYED', 'Cloud architect specializing in AWS and Azure. Experienced in containerization with Docker and Kubernetes. Building highly available distributed systems.'),
('AL-2017-015', 'Nikhil Choudhary', 'nikhil.choudhary@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2017', 'Mechanical Engineering', 'EMPLOYED', 'Senior mechanical engineer in aerospace industry. Working on aircraft component design and stress analysis. Deep knowledge of materials science and CFD simulations.'),
('AL-2018-016', 'Simran Kaur', 'simran.kaur@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2018', 'Computer Science', 'SELF_EMPLOYED', 'Blockchain developer and cryptocurrency enthusiast. Building decentralized applications on Ethereum and Solidity. Co-founder of a Web3 startup.'),
('AL-2020-017', 'Aditya Kulkarni', 'aditya.kulkarni@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2020', 'Civil Engineering', 'EMPLOYED', 'Urban planner working on smart city projects. Expertise in GIS, sustainable urban design, and traffic management systems. Focus on environmental impact assessment.'),
('AL-2021-018', 'Naina Saxena', 'naina.saxena@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2021', 'Electronics Engineering', 'SEEKING_OPPORTUNITIES', 'Fresh graduate interested in VLSI design and semiconductor technology. Completed projects on microprocessor design and digital signal processing. Seeking entry-level positions.'),
('AL-2022-019', 'Harsh Vardhan', 'harsh.vardhan@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2022', 'Electrical Engineering', 'EMPLOYED', 'Electrical design engineer in power distribution sector. Working with high voltage systems and electrical safety standards. Proficient in ETAP and electrical CAD software.'),
('AL-2023-020', 'Mehul Arora', 'mehul.arora@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqRzgVymGe07xd00DMxs.TVuHOn2', '2023', 'Computer Science', 'SEEKING_OPPORTUNITIES', 'Recent graduate passionate about web development and UI/UX design. Knowledge of HTML, CSS, JavaScript, and modern frameworks. Looking for frontend developer roles.');
